// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface MapDifficulty { notes: number, bombs: number, characteristic: string, difficulty: string, njs: number, nps: number, }