// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Player } from "./Player";

export interface Score { id: number, leaderboardPlayerInfo: Player, rank: number, baseScore: number, pp: number, badCuts: number, missedNotes: number, maxCombo: number, fullCombo: boolean, }