// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MapDifficulty } from "./MapDifficulty";

export interface Version { downloadURL: string, previewURL: string, coverURL: string, diffs: Array<MapDifficulty>, hash: string, }